var data = [
	{"nama": "Patience", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "51-60", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Rahim", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Joshua", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Nomlanga", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "41-50", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Uriel", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "21-30", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Jolie", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Cheyenne", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "51-60", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Kasimir", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "51-60", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Patience", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": ">8 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Sybill", "jenis_kelamin": "Perempuan", "status_nikah": "Janda/Duda", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Geoffrey", "jenis_kelamin": "Perempuan", "status_nikah": "Janda/Duda", "umur": "21-30", "gaji_pokok": "4-5,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Levi", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "21-30", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Abbot", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "41-50", "gaji_pokok": ">8 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Raymond", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "4-5,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Jasper", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "51-60", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Noel", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "41-50", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Brian", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "21-30", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Paula", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "41-50", "gaji_pokok": ">8 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Nathan", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "51-60", "gaji_pokok": ">8 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Genevieve", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "41-50", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Astra", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Curran", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "41-50", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Cameron", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "51-60", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Armand", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Chester", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "51-60", "gaji_pokok": ">8 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Noelle", "jenis_kelamin": "Perempuan", "status_nikah": "Janda/Duda", "umur": "21-30", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Clark", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "51-60", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Raven", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "41-50", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Dominic", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "21-30", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Victor", "jenis_kelamin": "Perempuan", "status_nikah": "Janda/Duda", "umur": "41-50", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Deborah", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "41-50", "gaji_pokok": ">8 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Addison", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "41-50", "gaji_pokok": "2-3,99 juta", "keloyalan": "Loyal"},
	{"nama": "Otto", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Tad", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "41-50", "gaji_pokok": "4-5,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Donovan", "jenis_kelamin": "Perempuan", "status_nikah": "Janda/Duda", "umur": "31-40", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Jackson", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "51-60", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Xerxes", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "21-30", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Branden", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "41-50", "gaji_pokok": ">8 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Quyn", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "51-60", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Dale", "jenis_kelamin": "Perempuan", "status_nikah": "Janda/Duda", "umur": "31-40", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Elvis", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "51-60", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Dawn", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "41-50", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Adam", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "41-50", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Maxine", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "21-30", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Raphael", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "41-50", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Jakeem", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "51-60", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Kirby", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "41-50", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Adrienne", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Ciaran", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "21-30", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Isaac", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "21-30", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Uta", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Andrew", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "21-30", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Lesley", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "41-50", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Kim", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "51-60", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Basil", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Myles", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "51-60", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Harding", "jenis_kelamin": "Perempuan", "status_nikah": "Janda/Duda", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Talon", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "4-5,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Castor", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "51-60", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Deacon", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "51-60", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Leilani", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "4-5,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Xaviera", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Baxter", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "41-50", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Carissa", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Loyal"},
	{"nama": "Robin", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "41-50", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Blaze", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Loyal"},
	{"nama": "Callum", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Logan", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "51-60", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Asher", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "Caldwell", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Nerea", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "51-60", "gaji_pokok": ">8 juta", "keloyalan": "Loyal"},
	{"nama": "William", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "51-60", "gaji_pokok": "2-3,99 juta", "keloyalan": "Loyal"},
	{"nama": "Adrienne", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "31-40", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Keefe", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "51-60", "gaji_pokok": "4-5,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Whilemina", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "41-50", "gaji_pokok": ">8 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Fulton", "jenis_kelamin": "Perempuan", "status_nikah": "Janda/Duda", "umur": "51-60", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Judith", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "41-50", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Elliott", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Loyal"},
	{"nama": "Halee", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Loyal"},
	{"nama": "Tucker", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Zephania", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Loyal"},
	{"nama": "Holmes", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "21-30", "gaji_pokok": "4-5,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Kiayada", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "21-30", "gaji_pokok": ">8 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Shellie", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "21-30", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Robert", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Steel", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "21-30", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Ian", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Paul", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "51-60", "gaji_pokok": "2-3,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Keane", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "51-60", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Lee", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "4-5,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Denise", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "21-30", "gaji_pokok": "4-5,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Addison", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "51-60", "gaji_pokok": "2-3,99 juta", "keloyalan": "Loyal"},
	{"nama": "Wyoming", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "4-5,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Eden", "jenis_kelamin": "Laki-laki", "status_nikah": "Janda/Duda", "umur": "31-40", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Ciara", "jenis_kelamin": "Perempuan", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": "6-7,99 juta", "keloyalan": "Loyal"},
	{"nama": "Cheyenne", "jenis_kelamin": "Laki-laki", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "2-3,99 juta", "keloyalan": "Loyal"},
	{"nama": "Mara", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"},
	{"nama": "Erica", "jenis_kelamin": "Perempuan", "status_nikah": "Nikah", "umur": "31-40", "gaji_pokok": "6-7,99 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Amery", "jenis_kelamin": "Laki-laki", "status_nikah": "Bujang", "umur": "31-40", "gaji_pokok": ">8 juta", "keloyalan": "Tidak Loyal"},
	{"nama": "Pamela", "jenis_kelamin": "Perempuan", "status_nikah": "Janda/Duda", "umur": "41-50", "gaji_pokok": "4-5,99 juta", "keloyalan": "Loyal"}
];
